import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import { IBM, poppins, ralway } from "./fonts";
import Animations from "@/components/Animations";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IBM.className} ${ralway.className} ${poppins.className} antialiased`}
      >
        {/* <Animations /> */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
